name: Build and Push SMB Container

on:
  workflow_call:
    inputs:
      smb_version:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/smb-server
          docker build -t $IMAGE_NAME:${{ inputs.smb_version }} .
          docker tag $IMAGE_NAME:${{ inputs.smb_version }} $IMAGE_NAME:latest

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/smb-server:${{ inputs.smb_version }}
          docker push ghcr.io/${{ github.repository_owner }}/smb-server:latest

      - name: Update Git tags
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      
          # Delete the existing tag if it exists
          if git rev-parse "smb-${{ inputs.smb_version }}" >/dev/null 2>&1; then
            git tag -d "smb-${{ inputs.smb_version }}"
            git push origin --delete "smb-${{ inputs.smb_version }}"
          fi
      
          # Create and push the new tag
          git tag "smb-${{ inputs.smb_version }}"
          git push origin "smb-${{ inputs.smb_version }}"
      
          # Update the 'latest' tag
          git tag -f latest
          git push origin latest --force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: smb-${{ inputs.smb_version }}
          name: "SMB Server ${{ inputs.smb_version }}"
          body: "A new version of the SMB server container has been built: **${{ inputs.smb_version }}**"
          draft: false
          prerelease: false
