name: Manual SMB Build

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:  # Only runs when manually triggered

jobs:
  get-latest-smb-version:
    runs-on: ubuntu-latest
    outputs:
      smb_version: ${{ steps.check.outputs.version }}
    steps:
      - name: Check latest Alpine SMB version
        id: check
        run: |
          LATEST_VERSION=$(curl -s https://pkgs.alpinelinux.org/package/edge/main/x86_64/samba | grep -oP '>\K[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
          echo "Latest SMB version: $LATEST_VERSION"
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

  build-and-push:
    needs: get-latest-smb-version
    uses: ./.github/workflows/build-and-push.yml  # Reuse the build workflow
    with:
      smb_version: ${{ needs.get-latest-smb-version.outputs.smb_version }}  # Use detected SMB version
