name: SMB Version Update

permissions:
  contents: write
  packages: write

on:
  schedule:
    - cron: '0 2 * * *'  # Dagelijks om 2:00 UTC
  workflow_dispatch:

jobs:
  check-smb-versions:
    runs-on: ubuntu-latest
    outputs:
      stable_version: ${{ steps.check.outputs.stable_version }}
      edge_version: ${{ steps.check.outputs.edge_version }}
      stable_needs_update: ${{ steps.compare.outputs.stable_needs_update }}
      edge_needs_update: ${{ steps.compare.outputs.edge_needs_update }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check latest SMB versions
        id: check
        run: |
          get_latest_smb_version() {
            local branch=$1
            curl -s "https://pkgs.alpinelinux.org/package/${branch}/main/x86_64/samba" | \
              grep -oP '>\K[0-9]+\.[0-9]+\.[0-9]+' | head -n 1
          }

          STABLE_VERSION=$(get_latest_smb_version "v$(curl -s https://dl-cdn.alpinelinux.org/alpine/ | grep -oP '(?<=href=")v[0-9]+\.[0-9]+(?=/")' | sort -V | tail -n 1 | tr -d 'v')")
          EDGE_VERSION=$(get_latest_smb_version "edge")

          echo "stable_version=$STABLE_VERSION" >> $GITHUB_OUTPUT
          echo "edge_version=$EDGE_VERSION" >> $GITHUB_OUTPUT

      - name: Compare with last built versions
        id: compare
        run: |
          git fetch --tags

          LAST_STABLE_VERSION=$(git tag --list 'smb-stable-*' | sort -V | tail -n 1 | sed 's/smb-stable-//')
          LAST_EDGE_VERSION=$(git tag --list 'smb-edge-*' | sort -V | tail -n 1 | sed 's/smb-edge-//')

          if [ "$LAST_STABLE_VERSION" != "${{ steps.check.outputs.stable_version }}" ]; then
            echo "stable_needs_update=true" >> $GITHUB_OUTPUT
          else
            echo "stable_needs_update=false" >> $GITHUB_OUTPUT
          fi

          if [ "$LAST_EDGE_VERSION" != "${{ steps.check.outputs.edge_version }}" ]; then
            echo "edge_needs_update=true" >> $GITHUB_OUTPUT
          else
            echo "edge_needs_update=false" >> $GITHUB_OUTPUT
          fi

  build-stable:
    needs: check-smb-versions
    if: needs.check-smb-versions.outputs.stable_needs_update == 'true'
    uses: ./.github/workflows/build-and-push.yml
    with:
      smb_version: ${{ needs.check-smb-versions.outputs.stable_version }}
      alpine_channel: stable

  build-edge:
    needs: check-smb-versions
    if: needs.check-smb-versions.outputs.edge_needs_update == 'true'
    uses: ./.github/workflows/build-and-push.yml
    with:
      smb_version: ${{ needs.check-smb-versions.outputs.edge_version }}
      alpine_channel: edge
