name: SMB Version Update

permissions:
  contents: write
  packages: write

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-smb-version:
    runs-on: ubuntu-latest
    outputs:
      smb_version: ${{ steps.check.outputs.version }}
      needs_update: ${{ steps.compare.outputs.needs_update }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all tags are fetched
          ref: main  # Make sure we are on the correct branch

      - name: Check latest Alpine SMB version
        id: check
        run: |
          ALPINE_VERSION=$(curl -s https://dl-cdn.alpinelinux.org/alpine/ | grep -oP '(?<=href=")v[0-9]+\.[0-9]+(?=/")' | sort -V | tail -n 1 | tr -d 'v')
          LATEST_VERSION=$(curl -s "https://pkgs.alpinelinux.org/package/v$ALPINE_VERSION/main/x86_64/samba" | grep -oP '>\K[0-9]+\.[0-9]+\.[0-9]+' | head -n 1)
          echo "Latest SMB version: $LATEST_VERSION"
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Compare with last built version
        id: compare
        run: |
          # Ensure we fetch all tags to compare correctly
          git fetch --tags

          # Get the last built version from tags
          LAST_BUILT_VERSION=$(git tag --list 'smb-*' | sort -V | tail -n 1 | sed 's/smb-//')

          echo "Last built version: $LAST_BUILT_VERSION"
          echo "Latest available SMB version: ${{ steps.check.outputs.version }}"

          # Compare versions
          if [ -z "$LAST_BUILT_VERSION" ]; then
            echo "No previous builds found. Proceeding to build."
            echo "needs_update=true" >> $GITHUB_ENV
          elif [ "$LAST_BUILT_VERSION" != "${{ steps.check.outputs.version }}" ]; then
            echo "New SMB version detected. Proceeding to build."
            echo "needs_update=true" >> $GITHUB_ENV
          else
            echo "No new SMB version. Skipping build."
            echo "needs_update=false" >> $GITHUB_ENV
          fi

  build-and-push:
    needs: check-smb-version
    if: env.needs_update == 'true'
    uses: ./.github/workflows/build-and-push.yml  # Reuse common build logic
    with:
      smb_version: ${{ needs.check-smb-version.outputs.smb_version }}
